---
- name: "Add libcontainer repository on CentOS"
  yum_repository:
    baseurl: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ ansible_distribution }}/devel:kubic:libcontainers:stable.repo" # noqa 204
    file: "/etc/yum.repos.d/devel:kubic:libcontainers:stable.repo"
    state: present

- name: "Add CRI-O repository on CentOS"
  yum_repository:
    baseurl: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ kubernetes_version }}/{{ ansible_distribution }}/devel:kubic:libcontainers:stable:cri-o:{{ kubernetes_version }}.repo" # noqa 204
    file: "/etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:{{ kubernetes_version }}.repo"

- name: "Install CRI-O on CentOS"
  yum:
    name: cri-o
    state: present